# DataSource Config
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/test?useSSL=true&requireSSL=false&serverTimezone=Asia/Shanghai
    username: root
    password: 12345678
    hikari:
      max-lifetime: 150000
      connection-test-query: select 1
  sql:
    init:
      schema-locations: classpath:db/schema-h2.sql
      data-locations: classpath:db/data-h2.sql
      mode: always


logging:
  level:
    com.aircjm.study.mybatisplus: debug

mybatis-plus:
  mapper-locations: classpath*:/mapper/*.xml
  configuration:
    log-impl: org.apache.ibatis.logging.slf4j.Slf4jImpl
    map-underscore-to-camel-case: true
    cache-enabled: false
    default-enum-type-handler: com.baomidou.mybatisplus.core.handlers.MybatisEnumTypeHandler
    local-cache-scope: session
  global-config:
    db-config:
      logic-delete-value: 1
      logic-not-delete-value: 0