server:
  port: 8085

spring:
  redis:
    host: 127.0.0.1
    port: 6379


knife4j:
  enable: true
  openapi:
    title: Knife4j官方文档
    description: "`我是测试`,**你知道吗**"


sdk:
  apiKey: 4857fb44-557c-4e4b-96a1-65




mail:
  apiKey: apikeyDemo
  uid: 3.1415
  send-email-result-url: "urlTest"
  subject: "demo"
  cc: a@demo.com,b@test.com


