server:
  port: 9080

# DataSource Config
spring:
  datasource:
    driver-class-name: org.sqlite.JDBC
    url: jdbc:sqlite:./test.db
    username: root
    password: test
  sql:
    init:
      schema-locations: classpath:db/schema-h2.sql
      data-locations: classpath:db/data-h2.sql
      mode: always

# Logger Config
logging:
  level:
    com.rimlook.mybatisplus.sqlite: debug


mybatis-plus:
  global-config:
    db-config:
      logic-delete-field: is_delete    # 逻辑删除字段
      logic-delete-value: 1           # 删除状态值(可选)
      logic-not-delete-value: 0       # 未删除状态值(可选)
      id-type: auto                   # 主键生成策略
      update-strategy: ignored       # 推荐使用非null更新策略
  configuration:
    cache-enabled: false              # 禁用二级缓存
    map-underscore-to-camel-case: true # 下划线转驼峰
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl # 日志输出(开发环境)
